name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Install just and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Run CI
        run: just ci
